# myapi/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ProductViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'products', ProductViewSet) # 'products' will be the base URL for product operations

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # Include the URLs generated by the router under the 'api/' path.
    # So, products will be accessible at 'api/products/'
    path('', include(router.urls)),
]
